overlay:
  baseunit: 100
  familyres:
    - family: C
      memcpuratio: 1.5
      limitreqratio: 1.2
    - family: M
      memcpuratio: 1.5
      limitreqratio: 1.2
    - family: G
      memcpuratio: 1
      limitreqratio: 1.1
    - family: B
      memcpuratio: 1
      limitreqratio: 2
  vmachines:
    v1: 1
    v2: 2
    v3: 3
    v4: 4
    v5: 5
    v6: 6
    v7: 7
    v8: 8
    v9: 9
